export const DEFAULTS = {
  settings: {
    siteName: 'Sushmit Energy',
    siteEmail: 'info@sushmitenergy.com',
    sitePhone: '+977-15199027',
    address: 'Sushmit Bhawan -2nd Floor, House No 166/40467, Subidhanagar - 35, Kathmandu, Nepal',
  },

  contact: {
    address: 'Sushmit Bhawan -2nd Floor, House No 166/40467\nSubidhanagar - 35, Kathmandu, Nepal',
    phone: '+977-15199027',
    fax: '+977-5199454',
    email: 'info@sushmitenergy.com',
    mapEmbed: '',
  },

  bannerSlides: [
    {
      img: "https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/IMG_7069.jpg",
      title: 'Experts in Hydro Power Project',
    },
    {
      img: "https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/slider4.jpg",
      title: 'We Build Better Hydro Project & Ensure Standing Wealth Creation.',
    },
    {
      img: "https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/Hydro-Village-Feasibility-Study-2.jpg",
      title: 'Future of Hydro Energy in Nepal',
    },
    {
      img: "https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/slider3.jpg",
      title: 'Pioneer in Innovation and Design',
    },
    {
      img: "https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/sliderhome.jpg",
      title: 'Clean & Sustainable Hydro Energy',
    },
  ],

  homeStats: [
    { value: '25', label: 'Engineers & Workers' },
    { value: '4', label: 'Projects In Progress' },
    { value: '93', label: 'Megawatt Generate' },
  ],

  homeAbout: {
    label: 'Welcome to',
    title: 'Sushmit Energy',
    text: "Sushmit Energy Pvt. Ltd is a leading hydropower project development company established with the aim of expanding hydro energy investment in Nepali market. We are currently working on four hydropower projects aimed at generating 93+ MW of electricity upon its completion. We specialize in the development and management of hydro projects with the aim of cost-effective investment and high level of profit to the investors and the nation as well.",
  },

  homeHistory: {
    text: 'Over 24 years of experience and knowledge of international standards, technological changes, and industrial systems.',
    years: ['2013', '2014', '2015', '2016'],
  },

  about: {
    title: 'About Sushmit Energy',
    subtitle: 'Leading hydropower development company in Nepal',
    paragraphs: [
      "Sushmit Energy Pvt. Ltd is a leading hydropower project development company established with the aim of expanding hydro energy investment in the Nepali market. We specialize in the development and management of hydro projects with the aim of cost-effective investment and high level of profit to the investors and the nation as well. We are continuously working for leading the hydro energy sectors and qualified us in investment engineering. We value the time, money and energy of our partners and guarantee the highest return possible.",
      "Sushmit Energy is currently working on four hydropower projects aimed at generating 93+ MW of electricity upon its completion. Backed by energy, financial and hydro experts, we can handle any size of project and accomplish the desired results.",
    ],
    vision: "We envision developing alternative and eco-friendly sources of energy by promoting people's participation, investment and advanced technology where the value of shareholders are maximized and better wealth is created.",
    mission: "We will create an atmosphere of investment for the people and ensure value of their profit increment by suggesting the best hydro product for investment, managing the company professionally, selecting the best products, and involving partnership in the sphere of energy investment.",
    objectives: "To be the hydropower production and investment experts which will ultimately provide our stakeholders a high value of shares and dignity to be associated with.",
  },

  boardMembers: [
    {
      name: 'Sushil Pokharel',
      title: 'Chairman',
      image: 'https://web.archive.org/web/20260121094210im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png',
      description: '',
      social: { facebook: 'https://www.facebook.com/sushilpokharel.NP', twitter: 'https://twitter.com/sushilpokharel1', linkedin: 'https://www.linkedin.com/in/sushilpokharel/' },
      order: 1,
    },
    {
      name: 'Bhawani Devkota',
      title: 'Director',
      image: 'https://web.archive.org/web/20260121094210im_/https://www.sushmitenergy.com/wp-content/uploads/2018/01/bhawani-Devkota-1.jpg',
      description: '',
      social: { facebook: 'https://www.facebook.com/bhawani.devkota.5' },
      order: 2,
    },
    {
      name: 'Subash C Baral',
      title: 'Director',
      image: 'https://web.archive.org/web/20260121094210im_/https://www.sushmitenergy.com/wp-content/uploads/2018/01/Subash-sir-photo.jpg',
      description: '',
      social: {},
      order: 3,
    },
    {
      name: 'Binod Dhakal',
      title: 'Director',
      image: 'https://web.archive.org/web/20260121094210im_/https://www.sushmitenergy.com/wp-content/uploads/2017/04/Binod-Dhakal.jpg',
      description: '',
      social: { facebook: 'https://www.facebook.com/binod.dhakal.583' },
      order: 4,
    },
    {
      name: 'Yadav Pokharel',
      title: 'Director',
      image: 'https://web.archive.org/web/20260121094210im_/https://www.sushmitenergy.com/wp-content/uploads/2017/04/19400098_10154699406841662_1875753842769488258_n.jpg',
      description: '',
      social: { facebook: 'https://www.facebook.com/yadabp', twitter: 'https://twitter.com/yadabpok', linkedin: 'https://www.linkedin.com/in/yad-pokharel-732a321b/' },
      order: 5,
    },
  ],

  managementTeam: [
    { name: 'Sushil Pokharel', title: 'Chairman', image: 'https://web.archive.org/web/20260315210330im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png', order: 1 },
    { name: 'Rajendra Shrestha', title: 'Managing Director', image: 'https://web.archive.org/web/20260315210330im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png', order: 2 },
    { name: 'Prakash Adhikari', title: 'Chief Operating Officer', image: 'https://web.archive.org/web/20260315210330im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png', order: 3 },
    { name: 'Anita Thapa', title: 'Chief Financial Officer', image: 'https://web.archive.org/web/20260315210330im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png', order: 4 },
    { name: 'Binod Acharya', title: 'Head of Engineering', image: 'https://web.archive.org/web/20260315210330im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png', order: 5 },
    { name: 'Sunita Sharma', title: 'Company Secretary', image: 'https://web.archive.org/web/20260315210330im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png', order: 6 },
  ],

  chairman: {
    title: 'Message from the Chairman',
    subtitle: 'Sushil Pokharel',
    name: 'Sushil Pokharel',
    role: 'Chairman, Sushmit Energy',
    image: 'https://web.archive.org/web/20250714064044im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png',
    heading: 'Dear Valued Investors',
    intro: 'Warm Greetings!',
    paragraphs: [
      "It is my pleasure to come up with the valuable information of the company which will further increase the probability of participation and investment in joint venture. With this message I would like to focus untapped sectors of investment where anybody can come and start investing.",
      "Endowed with the capacity of producing 43,000 MW, Nepal boasts considerable hydropower potential and will be instrumental in meeting the South Asian region's rapidly growing demand for a cost-effective and environmentally-friendly sustainable energy. The perennial qualities of Nepal's rivers and steep geographical declination provide ideal conditions for the development of hydropower projects throughout the nation. According to Department of Electricity Development, 1010 MW is being generated by hydropower plants across the country which means more than 90% of the country's water resources are yet to be harnessed.",
      "If all investors, individuals and the government coordinate to develop hydropower projects, the future of hydro energy in Nepal is brighter and profitable. Not only will it end the energy crisis but also play a pivotal role in generating revenue for the country as Nepal starts trading internationally.",
      "Sushmit Energy is currently working on hydropower projects that will generate 93+ MW as soon as they are completed. — Four of them being — Myagdi Khola Hydropower Project (57.3 MW), Kunaban Khola Hydropower Project (24.78 MW), Myagdi Khola – B Hydropower Project (9.5 MW), Lower Selang Khola Hydropower Project (1.475 MW). We plan on generating 100 MW in the first five years which is going to be completed and an additional 500 MW in the next five years. Our team is working for a greater purpose that would both make Nepal prosperous and also maximize the wealth of our investors and shareholders concurrently.",
    ],
    quote:
      "It is my pleasure to come up with the valuable information of the company which will further increase the probability of participation and investment in joint venture. With this message I would like to focus untapped sectors of investment where anybody can come and start investing.",
    signoff: 'Regards,',
  },

  orgChart: {
    title: 'Organizational Structure',
    subtitle: 'Our organizational framework',
    image: 'https://web.archive.org/web/20250714064752im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/organization-chart.png',
  },

  investment: {
    title: 'Investment Opportunity in Nepal',
    subtitle: "Harness Nepal's vast hydropower potential",
    heading: 'Sector Overview',
    paragraphs: [
      "Nepal is rich in water resources with multiple sources of water, including glaciers, snowmelt from the Himalayas, rainfall and ground water. There are 6,000 rivers, including rivulets and tributaries, totalling about 45,000 km in length. The country contains 2.2% of the world's water resources.",
      "Nepal's theoretical capacity for producing power from hydropower projects is around 80,000 MW. However, as at 2014, installed capacity is only around 700 MW of electricity, despite the fact that demand is over 1,000 MW. Thus, Nepal remains one of the lowest energy consuming countries in the world. Demand for electricity is increasing at 7–9% per year, and according to the forecast from Nepal Electricity Authority, demand for electricity will reach 3,600 MW by 2027.",
      "To deal with the shortage of electricity in Nepal, IBN and other government agencies have stepped forward to implement mega hydropower projects. In September 2014, Nepal signed its first Project Development Agreement (PDA, concession agreement) with a private developer, GMR LTD, to develop the Upper Karnali Hydropower Project, a 900 MW project. IBN has also signed another PDA with SJVNL, an Indian governmental entity, for the development of the 900 MW Arun III. The combined cost of these two projects exceeds USD 2.5 billion. In addition, Nepal has signed the Power Trade Agreement (PTA) with India, paving the way for the free flow of electricity as a commodity across the border.",
      "There are several other mega power projects (above 500 MW) in the early stages of development, and IBN has the mandate to take these projects forward. These projects are a high priority for the government and various incentives are in place for investors.",
    ],
    links: [
      { name: 'Nepal Investment Summit', url: 'http://investmentsummitnepal.com/' },
      { name: 'Government of Nepal Ministry of Energy', url: 'http://www.moen.gov.np/' },
      { name: 'Nepal Electricity Authority', url: 'http://www.nea.org.np/' },
      { name: 'Department of Electricity Development (DOED)', url: 'http://www.doed.gov.np/' },
      { name: 'Department of Land Reform and Management', url: 'http://www.dolrm.gov.np/' },
    ],
    resources: [
      { name: 'Nepal Investment Guide 2018 - English Version', file: 'http://ibn.gov.np/uploads/files/repository/Nepal%20Investment%20Guide%202018.pdf' },
      { name: 'Nepal Investment Guide 2018 - Chinese Version', file: 'http://ibn.gov.np/uploads/files/repository/IBN_Investment%20Guide%20Book_Chinese.pdf' },
      { name: 'Nepal Investment Guide 2018 - Japanese Version', file: 'http://www.ibn.gov.np/uploads/files/repository/IBN_Investment%20Guide%20Book_Japanese_Final.pdf' },
    ],
  },

  projects: [
    {
      name: 'Myagdi Khola Hydropower Project',
      subtitle: '57.3 MW run-of-river hydropower project in Myagdi District',
      slug: 'myagdi-khola-hydropower-project',
      capacity: '57.3 MW',
      location: 'Myagdi District, Gandaki Province',
      status: 'Under Development',
      startDate: '2024',
      type: 'Run-of-River',
      river: 'Myagdi Khola',
      annualEnergy: '~300 GWh',
      overview:
        "The Myagdi Khola Hydropower Project is Sushmit Energy's flagship venture, representing a significant investment in Nepal's renewable energy infrastructure. This 57.3 MW run-of-river hydropower project is located in the Myagdi District of Gandaki Province, harnessing the flow of the Myagdi Khola river. The project is designed to generate clean, sustainable electricity that will contribute to Nepal's national grid, helping to meet the country's growing energy demands while reducing reliance on fossil fuel-based power generation.",
      features: [
        'Run-of-river design minimizing environmental impact',
        'Annual energy generation of approximately 300 GWh',
        'State-of-the-art turbine and generator technology',
        'Comprehensive fish passage and environmental mitigation measures',
        'Community development programs in surrounding areas',
      ],
      image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/slider1-1024x576.jpg',
      published: true,
    },
    {
      name: 'Kunaban Khola Hydropower Project',
      subtitle: '24.78 MW run-of-river hydropower project',
      slug: 'kunaban-khola-hydropower-project',
      capacity: '24.78 MW',
      location: 'Kunaban Khola',
      status: 'Under Development',
      startDate: '2023',
      type: 'Run-of-River',
      river: 'Kunaban Khola',
      annualEnergy: '~130 GWh',
      overview:
        "The Kunaban Khola Hydropower Project is a 24.78 MW medium-capacity hydropower project developed by Sushmit Energy. The project is designed to efficiently utilize the water resources of the Kunaban Khola river, contributing to the sustainable development of Nepal's energy sector. As a run-of-river project, it minimizes environmental impact while generating clean, renewable electricity. The project represents Sushmit Energy's commitment to expanding Nepal's hydropower capacity through well-planned, environmentally responsible development.",
      features: [
        'Run-of-river design with minimal ecological footprint',
        'Annual energy generation of approximately 130 GWh',
        'Efficient turbine technology for optimal water utilization',
        'Community engagement and local employment programs',
        'Environmentally sustainable construction practices',
      ],
      image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/04/imageforsusmit-1024x576.png',
      published: true,
    },
    {
      name: 'Myagdi Khola B Hydropower Project',
      subtitle: '12.5 MW run-of-river hydropower project',
      slug: 'myagdi-khola-b-hydropower-project',
      capacity: '12.5 MW',
      location: 'Myagdi District, Gandaki Province',
      status: 'Commissioned',
      startDate: '2025',
      type: 'Run-of-River',
      river: 'Myagdi Khola',
      annualEnergy: '~65 GWh',
      overview:
        'The Myagdi Khola-B Hydropower Project is a 12.5 MW run-of-river project that complements the main Myagdi Khola Hydropower Project. Located in the Myagdi District, this secondary project maximizes the hydroelectric potential of the Myagdi Khola watershed. As a recently commissioned project, Myagdi Khola-B represents the successful execution of Sushmit Energy\'s strategy to develop multiple projects within the same river basin, optimizing infrastructure investment and minimizing environmental impact.',
      features: [
        'Successfully commissioned and operational',
        'Annual energy generation of approximately 65 GWh',
        'Complements the main Myagdi Khola project infrastructure',
        'Minimal additional environmental impact through shared facilities',
        "Contributes to Nepal's energy security",
      ],
      image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/04/imagfor2-1024x576.jpg',
      published: true,
    },
  ],

  galleryAlbums: [
    {
      name: 'Myagdi Khola Hydropower Project',
      cover: 'https://web.archive.org/web/20260121105521im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/slider2-1024x576.jpg',
      link: '/myagdi-khola-hydropower-project/',
      description: '',
      images: [],
    },
    {
      name: 'Kunaban Khola Hydropower Project',
      cover: 'https://web.archive.org/web/20260121105521im_/https://www.sushmitenergy.com/wp-content/uploads/2017/04/imageforsusmit-1024x576.png',
      link: '/kunaban-khola-hydropower-project/',
      description: '',
      images: [],
    },
    {
      name: 'Myagdi Khola-B Hydropower Project',
      cover: 'https://web.archive.org/web/20260121105521im_/https://www.sushmitenergy.com/wp-content/uploads/2017/11/11.jpg',
      link: '/myagdi-khola-b-hydropower-project/',
      description: '',
      images: [],
    },
  ],

  news: {
    'Press Release': [
      {
        title: 'Sushmit Energy Announces Successful Commissioning of Myagdi Khola-B Project',
        date: 'March 15, 2026',
        summary: "Sushmit Energy Pvt. Ltd. is pleased to announce the successful commissioning of its 12.5 MW Myagdi Khola-B Hydropower Project, marking a significant milestone in the company's expansion of clean energy generation in Nepal.",
        category: 'Press Release',
        source: '',
      },
      {
        title: 'Sushmit Energy Reports Strong Financial Performance for Fiscal Year 2024/25',
        date: 'January 28, 2026',
        summary: 'The Board of Directors of Sushmit Energy Pvt. Ltd. has announced impressive financial results for the fiscal year 2024/25, with revenue growth driven by increased power generation across all operational projects.',
        category: 'Financial',
        source: '',
      },
      {
        title: 'Sushmit Energy Partners with International Investors for New Hydro Projects',
        date: 'November 10, 2025',
        summary: 'Sushmit Energy has entered into a strategic partnership agreement with international investors to develop new hydropower projects with a combined capacity of 50 MW in the Karnali Province.',
        category: 'Press Release',
        source: '',
      },
      {
        title: 'Sushmit Energy Wins "Best Hydropower Developer" Award at Nepal Energy Summit 2025',
        date: 'September 5, 2025',
        summary: "Sushmit Energy was honored with the \"Best Hydropower Developer\" award at the Nepal Energy Summit 2025, recognizing the company's outstanding contributions to Nepal's renewable energy sector.",
        category: 'Award',
        source: '',
      },
      {
        title: 'Community Development Initiatives Launched in Myagdi Project Areas',
        date: 'July 22, 2025',
        summary: 'As part of its corporate social responsibility program, Sushmit Energy has launched comprehensive community development initiatives in the Myagdi district, focusing on education, healthcare, and infrastructure.',
        category: 'CSR',
        source: '',
      },
      {
        title: 'Sushmit Energy Achieves ISO Certification for Environmental Management',
        date: 'May 18, 2025',
        summary: "Sushmit Energy has successfully achieved ISO 14001:2015 certification for its environmental management systems, demonstrating the company's commitment to sustainable hydropower development.",
        category: 'Press Release',
        source: '',
      },
    ],
    News: [
      {
        title: 'Sushmit Energy Completes 57.3 MW Myagdi Khola Project Feasibility Studies',
        date: 'February 20, 2026',
        summary: "Detailed feasibility studies for the flagship 57.3 MW Myagdi Khola Hydropower Project have been successfully completed, confirming the project's technical and financial viability.",
        source: 'The Himalayan Times',
        category: 'News',
      },
      {
        title: 'Sushmit Energy to Invest NPR 2 Billion in Renewable Energy Expansion',
        date: 'December 12, 2025',
        summary: 'Sushmit Energy has announced plans to invest NPR 2 billion over the next three years to expand its renewable energy portfolio, including new hydro and solar projects across Nepal.',
        source: 'Kathmandu Post',
        category: 'News',
      },
      {
        title: 'Sushmit Energy Creates 500+ Jobs Through Hydropower Development',
        date: 'October 8, 2025',
        summary: 'Through its ongoing hydropower projects in Myagdi and other districts, Sushmit Energy has created over 500 direct and indirect employment opportunities for local communities.',
        source: 'Nepal Energy News',
        category: 'News',
      },
      {
        title: "Nepal's Hydropower Sector Attracts Foreign Investment Through Companies Like Sushmit Energy",
        date: 'August 15, 2025',
        summary: "Nepal's hydropower sector is seeing increased foreign direct investment, with companies like Sushmit Energy leading the way in sustainable project development and international partnerships.",
        source: 'The Rising Nepal',
        category: 'News',
      },
      {
        title: 'Sushmit Energy Contributes to National Grid Stability with Consistent Power Supply',
        date: 'June 3, 2025',
        summary: "Sushmit Energy's operational projects have been consistently contributing to Nepal's national grid, helping to reduce load-shedding hours during the dry season.",
        source: 'Republica',
        category: 'News',
      },
    ],
    Energy: [
      {
        title: "Nepal's Hydropower Potential: Current Status and Future Prospects",
        date: 'March 10, 2026',
        summary: "Nepal has an estimated hydropower potential of 83,000 MW, of which only about 3% has been developed. This article explores the current state of the sector and the immense opportunities ahead.",
        category: 'Industry Analysis',
        source: '',
      },
      {
        title: 'Government Announces New Policy to Boost Renewable Energy Investment',
        date: 'February 5, 2026',
        summary: 'The Government of Nepal has unveiled a new renewable energy policy offering tax incentives and streamlined approval processes to attract both domestic and foreign investment in the energy sector.',
        category: 'Policy Update',
        source: '',
      },
      {
        title: "Regional Power Trade: Nepal's Role in South Asian Energy Security",
        date: 'January 18, 2026',
        summary: "With cross-border electricity trade agreements in place, Nepal is positioning itself as a key energy exporter in South Asia, with potential to supply power to India, Bangladesh, and beyond.",
        category: 'Regional News',
        source: '',
      },
      {
        title: 'Climate Resilience in Hydropower: Adapting to Changing Weather Patterns',
        date: 'December 22, 2025',
        summary: 'As climate change affects glacial melt and rainfall patterns, Nepali hydropower developers are adopting new technologies and strategies to ensure long-term project viability.',
        category: 'Technology',
        source: '',
      },
      {
        title: 'Nepal Electricity Authority Reports Surplus Power Generation',
        date: 'November 8, 2025',
        summary: "For the first time in its history, Nepal has achieved surplus electricity generation during the wet season, marking a major milestone in the country's energy journey.",
        category: 'Market Update',
        source: '',
      },
      {
        title: 'Hydropower and Sustainable Development: Balancing Energy and Environment',
        date: 'September 30, 2025',
        summary: 'Experts discuss how run-of-river hydropower projects can coexist with environmental conservation, highlighting best practices from successful projects across Nepal.',
        category: 'Sustainability',
        source: '',
      },
    ],
    Blog: [
      {
        title: 'The Future of Hydropower in Nepal: Opportunities and Challenges',
        date: 'March 5, 2026',
        author: 'Sushmit Energy Team',
        category: 'Industry Insights',
        excerpt: "As Nepal continues to harness its vast hydropower potential, the sector faces both unprecedented opportunities and significant challenges that will shape the country's energy future.",
        image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/slider1-1024x576.jpg',
      },
      {
        title: 'How Run-of-River Hydropower Projects Minimize Environmental Impact',
        date: 'February 18, 2026',
        author: 'Sushmit Energy Team',
        category: 'Technology',
        excerpt: 'Run-of-river hydropower projects offer a sustainable alternative to large dams, generating clean electricity while significantly reducing environmental and social impacts.',
        image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/04/imageforsusmit-1024x576.png',
      },
      {
        title: 'Community Development Through Hydropower: A Case Study from Myagdi',
        date: 'January 22, 2026',
        author: 'Sushmit Energy Team',
        category: 'Community',
        excerpt: "Sushmit Energy's community development initiatives in Myagdi district demonstrate how hydropower projects can create lasting positive change for local communities.",
        image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/04/imagfor2-1024x576.jpg',
      },
      {
        title: "Understanding Nepal's Electricity Market: From Deficit to Surplus",
        date: 'December 10, 2025',
        author: 'Sushmit Energy Team',
        category: 'Market Analysis',
        excerpt: "Nepal's electricity market has undergone a remarkable transformation from chronic power deficits to seasonal surpluses. This article explores the journey and what lies ahead.",
        image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/slider2-1024x576.jpg',
      },
      {
        title: "Investment Opportunities in Nepal's Renewable Energy Sector",
        date: 'November 5, 2025',
        author: 'Sushmit Energy Team',
        category: 'Investment',
        excerpt: "With favorable government policies and immense untapped potential, Nepal's renewable energy sector offers compelling investment opportunities for domestic and international investors.",
        image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/themes/sushmitenergy/images/kulekhani.jpg',
      },
      {
        title: 'Women in Energy: Empowering Female Professionals in Hydropower',
        date: 'September 28, 2025',
        author: 'Sushmit Energy Team',
        category: 'Diversity',
        excerpt: 'Sushmit Energy is committed to promoting gender diversity in the traditionally male-dominated hydropower sector through targeted hiring and professional development programs.',
        image: 'https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/uploads/2017/03/slider1-1024x576.jpg',
      },
    ],
  },

  mediaKit: [
    {
      title: 'Sushmit Energy Company Profile',
      description: 'Complete company overview including project portfolio, management team, and financial highlights.',
      type: 'PDF',
      size: '2.4 MB',
      fileUrl: '',
      group: 'media-kit',
    },
    {
      title: 'Logo Pack (PNG + SVG)',
      description: 'Official Sushmit Energy logo in various formats and resolutions for print and digital use.',
      type: 'ZIP',
      size: '1.8 MB',
      fileUrl: '',
      group: 'media-kit',
    },
    {
      title: 'Project Photo Gallery (High Resolution)',
      description: 'High-resolution photos of our hydropower projects, suitable for publications and presentations.',
      type: 'ZIP',
      size: '15.6 MB',
      fileUrl: '',
      group: 'media-kit',
    },
    {
      title: 'Corporate Brochure',
      description: 'Printed-quality brochure detailing our mission, vision, projects, and investment opportunities.',
      type: 'PDF',
      size: '4.2 MB',
      fileUrl: '',
      group: 'media-kit',
    },
    {
      title: 'Brand Guidelines',
      description: 'Official brand usage guidelines including color palette, typography, and logo usage rules.',
      type: 'PDF',
      size: '1.1 MB',
      fileUrl: '',
      group: 'media-kit',
    },
    {
      title: 'Company Overview Video',
      description: "A short promotional video showcasing Sushmit Energy's projects and commitment to clean energy.",
      type: 'MP4',
      size: '48 MB',
      fileUrl: '',
      group: 'media-kit',
    },
  ],

  publications: [
    {
      title: 'Annual Report 2024/25',
      date: 'October 2025',
      description: 'Comprehensive annual report detailing financial performance, project updates, and corporate governance for the fiscal year 2024/25.',
      type: 'Annual Report',
      size: '5.2 MB',
      fileUrl: '',
      group: 'publications',
    },
    {
      title: 'Quarterly Progress Report - Q2 2025/26',
      date: 'January 2026',
      description: 'Quarterly update on project milestones, power generation statistics, and financial highlights for the second quarter.',
      type: 'Quarterly Report',
      size: '1.8 MB',
      fileUrl: '',
      group: 'publications',
    },
    {
      title: 'Environmental Impact Assessment: Myagdi Khola Project',
      date: 'March 2025',
      description: 'Detailed environmental impact assessment report for the 57.3 MW Myagdi Khola Hydropower Project, including mitigation measures.',
      type: 'EIA Report',
      size: '12.4 MB',
      fileUrl: '',
      group: 'publications',
    },
    {
      title: 'Social Impact Assessment: Kunaban Khola Project',
      date: 'January 2025',
      description: 'Social impact assessment examining the effects of the Kunaban Khola project on local communities and proposed benefit-sharing mechanisms.',
      type: 'SIA Report',
      size: '8.6 MB',
      fileUrl: '',
      group: 'publications',
    },
    {
      title: 'Corporate Social Responsibility Report 2024',
      date: 'April 2025',
      description: 'Overview of CSR initiatives undertaken by Sushmit Energy including education, healthcare, and infrastructure development programs.',
      type: 'CSR Report',
      size: '3.1 MB',
      fileUrl: '',
      group: 'publications',
    },
    {
      title: 'Technical Feasibility Study: Myagdi Khola-B Extension',
      date: 'November 2024',
      description: 'Technical feasibility study examining the extension potential of the Myagdi Khola-B project with updated resource assessment.',
      type: 'Technical Report',
      size: '9.7 MB',
      fileUrl: '',
      group: 'publications',
    },
  ],

  reports: {
    Annual: [
      { title: 'Annual Report 2024/25', date: 'October 2025', size: '4.8 MB', fileUrl: '', type: 'Annual' },
      { title: 'Annual Report 2023/24', date: 'October 2024', size: '4.5 MB', fileUrl: '', type: 'Annual' },
      { title: 'Annual Report 2022/23', date: 'October 2023', size: '4.2 MB', fileUrl: '', type: 'Annual' },
    ],
    Quarterly: [
      { title: 'Q3 2025/26', date: 'Jan–Mar 2026', size: '1.2 MB', fileUrl: '', type: 'Quarterly' },
      { title: 'Q2 2025/26', date: 'Oct–Dec 2025', size: '1.1 MB', fileUrl: '', type: 'Quarterly' },
      { title: 'Q1 2025/26', date: 'Jul–Sep 2025', size: '1.3 MB', fileUrl: '', type: 'Quarterly' },
    ],
  },

  policy: {
    title: 'Policy',
    subtitle: 'Energy policies and regulatory framework',
    heading: 'Energy Profile and Policy of Nepal',
    description: "Comprehensive document covering Nepal's energy sector profile, policies, and regulatory framework for hydropower development and investment.",
    fileUrl: 'https://web.archive.org/web/20260121104039/https://www.sushmitenergy.com/wp-content/uploads/2017/12/Energy-Sector.pdf',
  },

  jobs: [
    {
      title: 'Senior Hydropower Engineer',
      department: 'Engineering',
      location: 'Kathmandu, Nepal',
      type: 'Full-Time',
      deadline: '2026-08-30',
      description: "We are seeking an experienced Senior Hydropower Engineer to lead the technical design and implementation of our ongoing hydropower projects in western Nepal.",
      requirements: [
        "Bachelor's degree in Civil/Mechanical/Electrical Engineering",
        '8+ years of experience in hydropower project development',
        'Experience with feasibility studies and detailed engineering',
        'Strong project management and team leadership skills',
      ],
      status: 'Open',
    },
    {
      title: 'Environmental Compliance Officer',
      department: 'Environment & CSR',
      location: 'Myagdi, Nepal',
      type: 'Full-Time',
      deadline: '2026-08-15',
      description: 'Responsible for ensuring environmental compliance across all project sites and coordinating with regulatory bodies on environmental impact assessments.',
      requirements: [
        "Master's degree in Environmental Science or related field",
        '5+ years of experience in environmental compliance',
        "Knowledge of Nepal's environmental regulations and EIA processes",
        'Experience working on hydropower or infrastructure projects',
      ],
      status: 'Open',
    },
    {
      title: 'Finance Manager',
      department: 'Finance',
      location: 'Kathmandu, Nepal',
      type: 'Full-Time',
      deadline: '2026-09-15',
      description: "Manage the company's financial operations including budgeting, forecasting, investor reporting, and compliance with financial regulations.",
      requirements: [
        'CA or MBA in Finance from a recognized institution',
        '7+ years of experience in financial management',
        'Experience in the energy or infrastructure sector preferred',
        'Strong knowledge of Nepal tax laws and financial reporting standards',
      ],
      status: 'Open',
    },
    {
      title: 'Community Relations Officer',
      department: 'CSR & Community Development',
      location: 'Myagdi, Nepal',
      type: 'Full-Time',
      deadline: '2026-08-20',
      description: 'Serve as the primary liaison between the company and local communities, managing stakeholder engagement and community development programs.',
      requirements: [
        "Bachelor's degree in Social Sciences, Rural Development, or related field",
        '3+ years of experience in community relations',
        'Excellent communication and negotiation skills',
        'Fluency in Nepali and English, knowledge of local dialects preferred',
      ],
      status: 'Open',
    },
    {
      title: 'Junior Electrical Engineer',
      department: 'Engineering',
      location: 'Kathmandu, Nepal',
      type: 'Full-Time',
      deadline: '2026-09-01',
      description: 'Assist in the design, installation, and maintenance of electrical systems across our hydropower projects under the guidance of senior engineers.',
      requirements: [
        "Bachelor's degree in Electrical Engineering",
        '0–2 years of experience (fresh graduates encouraged to apply)',
        'Knowledge of power systems and electrical design software',
        'Willingness to work at project sites in remote areas',
      ],
      status: 'Open',
    },
  ],
};
