import Header from '../../components/Header';
import Footer from '../../components/Footer';
import { Quote } from 'lucide-react';

export default function ChairmanMessagePage() {
  return (
    <>
      <Header />
      <main>
        <section className="page-banner">
          <div className="page-banner-overlay" />
          <div className="container">
            <h1>Message from the Chairman</h1>
            <p>Sushil Pokharel</p>
          </div>
        </section>

        <section className="section-padding">
          <div className="container">
            <div className="chairman-page-layout">
              <div className="chairman-page-img">
                <img
                  src="https://web.archive.org/web/20250714064044im_/https://www.sushmitenergy.com/wp-content/uploads/2017/01/sushil-pokharel.png"
                  alt="Sushil Pokharel"
                />
              </div>
              <div className="chairman-page-content">
                <Quote size={48} className="chairman-quote-icon" />
                <h2>Dear Valued Investors</h2>
                <p>Warm Greetings!</p>
                <p>
                  It is my pleasure to come up with the valuable information of the company which
                  will further increase the probability of participation and investment in joint
                  venture. With this message I would like to focus untapped sectors of investment
                  where anybody can come and start investing.
                </p>
                <p>
                  Endowed with the capacity of producing 43,000 MW, Nepal boasts considerable
                  hydropower potential and will be instrumental in meeting the South Asian
                  region&apos;s rapidly growing demand for a cost-effective and
                  environmentally-friendly sustainable energy. The perennial qualities of
                  Nepal&apos;s rivers and steep geographical declination provide ideal conditions
                  for the development of hydropower projects throughout the nation. According to
                  Department of Electricity Development, 1010 MW is being generated by hydropower
                  plants across the country which means more than 90% of the country&apos;s water
                  resources are yet to be harnessed.
                </p>
                <p>
                  If all investors, individuals and the government coordinate to develop hydropower
                  projects, the future of hydro energy in Nepal is brighter and profitable. Not
                  only will it end the energy crisis but also play a pivotal role in generating
                  revenue for the country as Nepal starts trading internationally.
                </p>
                <p>
                  Sushmit Energy is currently working on hydropower projects that will generate
                  93+ MW as soon as they are completed. &mdash; Four of them being &mdash; Myagdi
                  Khola Hydropower Project (57.3 MW), Kunaban Khola Hydropower Project (24.78 MW),
                  Myagdi Khola &ndash; B Hydropower Project (9.5 MW), Lower Selang Khola
                  Hydropower Project (1.475 MW). We plan on generating 100 MW in the first five
                  years which is going to be completed and an additional 500 MW in the next five
                  years. Our team is working for a greater purpose that would both make Nepal
                  prosperous and also maximize the wealth of our investors and shareholders
                  concurrently.
                </p>
                <div className="chairman-signoff">
                  <p>Regards,</p>
                  <strong>Sushil Pokharel</strong>
                  <span>Chairman, Sushmit Energy</span>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />

      <style>{`
        .page-banner {
          position: relative;
          padding: 100px 0;
          background: linear-gradient(135deg, var(--primary-blue-dark), var(--primary-blue));
          text-align: center;
          color: white;
        }
        .page-banner-overlay {
          position: absolute;
          inset: 0;
          background: url('https://web.archive.org/web/20260414064744im_/https://www.sushmitenergy.com/wp-content/themes/sushmitenergy/images/kulekhani.jpg') center/cover no-repeat;
          opacity: 0.1;
        }
        .page-banner .container { position: relative; z-index: 1; }
        .page-banner h1 { font-size: 2.5rem; font-weight: 800; margin-bottom: 12px; }
        .page-banner p { font-size: 1.1rem; opacity: 0.85; }
        .chairman-page-layout {
          display: grid;
          grid-template-columns: 300px 1fr;
          gap: 50px;
          align-items: start;
          max-width: 1000px;
          margin: 0 auto;
        }
        .chairman-page-img {
          border-radius: var(--radius-lg);
          overflow: hidden;
          box-shadow: var(--shadow-lg);
          border: 4px solid var(--primary-green);
        }
        .chairman-page-img img {
          width: 100%;
          height: auto;
          display: block;
        }
        .chairman-page-content {
          position: relative;
        }
        .chairman-quote-icon {
          color: var(--primary-green);
          opacity: 0.15;
          margin-bottom: 20px;
        }
        .chairman-page-content h2 {
          font-size: 1.5rem;
          margin-bottom: 20px;
          color: var(--primary-blue);
        }
        .chairman-page-content p {
          font-size: 1rem;
          line-height: 1.8;
          color: var(--text-muted);
          margin-bottom: 16px;
          text-align: justify;
        }
        .chairman-signoff {
          margin-top: 30px;
          padding-top: 20px;
          border-top: 2px solid var(--border-color);
        }
        .chairman-signoff p { margin-bottom: 8px; }
        .chairman-signoff strong {
          display: block;
          font-size: 1.1rem;
          color: var(--text-dark);
        }
        .chairman-signoff span {
          font-size: 0.9rem;
          color: var(--text-muted);
        }
        @media (max-width: 768px) {
          .chairman-page-layout {
            grid-template-columns: 1fr;
            gap: 30px;
          }
          .chairman-page-img {
            max-width: 250px;
            margin: 0 auto;
          }
          .page-banner h1 { font-size: 1.8rem; }
        }
      `}</style>
    </>
  );
}
